// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback:                       1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    update_attributes
    (
        init => init
        upgrade => upgrade
        issue => issue
        create => create
        update => update
        send_nft => send_nft
        nft_token_id => nft_token_id
    )
}

multiversx_sc_wasm_adapter::async_callback! { update_attributes }
